### ISSUE TITLE
TCL compile issue Mavericks

### ISSUE THREAD

**Issue by joaoponceleao** [petere/homebrew-postgresql#14]
This is somewhat related to issue #3 in that I can't get postgresql 9.3 to compile without editing the formula beforehand. The difference is that I'm on Mavericks.
Specifically, I have to add the following to the formula (for homebrew's own tcl):
`--with-tclconfig=/usr/local/Cellar/tcl-tk/8.6.3/lib`

Looking at the 'normal' postgresql homebrew formula, it seems they add something similar (in this case they seem to look for Apple's own tcl.sh inside Xcode):
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/postgresql.rb#L64

Is there someway that we can update the recipe here to deal with this (considering that the location of the homebrew tcl lib is dependent on the version number)? This is not a big issue, but a bit annoying to have to re-edit the formula every time there is an update.

**Comment by petere** [comment]
Well, the fix for #3 was to add a dependency on `tcl-tk` to the formula, but this was later removed because it was no longer necessary.  I had [asked](http://librelist.com/browser//homebrew/2013/8/22/status-of-tcl-on-os-x-10-9/) on the Homebrew mailing list about it, but no one responded.  Also note that the CI build on Travis CI runs on Mavericks and [builds fine](https://travis-ci.org/petere/homebrew-postgresql/jobs/50861518).  So I'm confused.

**Comment by joaoponceleao** [comment]
Thanks for looking into it. The issue I have, and the fix I mentioned above, is identical to what is mentioned in the links you provided in the homebrew mailing list (I remember getting this issue from time to time with homebrew's main postgres package as well). I checked the build log you linked, to see if there were any tcl files postgres looks for missing on my system, but they're all there (i.e. both apple's and homebrew's tcl at `/usr/...` and `/usr/local...`). As this happened to other people with other packages, its obviously not just to do with this recipe (and might very well be just my system), but - short of doing a couple of brew installs and sending you the logs - I'm not sure what to do.
Its not a big issue at all, just annoying since I have to checkout, and re-edit the recipe every time there's an update to the tap.

**Comment by joaoponceleao** [comment]
Just to confirm that postgres builds nicely now with no need to edit the recipe after the latest commit. Thanks!
