### ISSUE TITLE
Newly added bottles don't work on Yosemite

### ISSUE THREAD

**Issue by RR2DO2** [petere/homebrew-postgresql#15]
Just installed postgres-9.4 on 10.10.2 and postgres won't start:

```
bash-3.2$ /usr/local/Cellar/postgresql-9.4/9.4.1/bin/postgres -v
dyld: Library not loaded: /usr/local/lib/libldap-2.4.2.dylib
  Referenced from: /usr/local/Cellar/postgresql-9.4/9.4.1/bin/postgres
  Reason: image not found
Trace/BPT trap: 5
```

Installing from source with brew install  --build-from-source  works fine.

**Comment by petere** [comment]
`brew install openldap`

I'll fix it.

**Comment by sylvesterjakubowski** [comment]
Same issue for postgres-9.1 on 10.10.2

**Comment by kdobrik** [comment]
Hi guys,
I have problem with the postgresql-9.3 installation. What I did is:

brew tap petere/postgresql
brew install postgresql-9.3

Then I tried:

initdb /usr/local/var/postgres-9.3 -E utf8
dyld: Library not loaded: /usr/local/lib/libldap-2.4.2.dylib
  Referenced from: /usr/local/Cellar/postgresql-9.3/9.3.9/bin/postgres
  Reason: image not found
no data was returned by command ""/usr/local/Cellar/postgresql-9.3/9.3.9/bin/postgres" -V"
The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/local/Cellar/postgresql-9.3/9.3.9/bin/initdb".
Check your installation.

MacAir:~ user$ brew install openldap
Warning: homebrew/dupes/openldap-2.4.41_1 already installed

In /usr/local/Cellar/postgresql-9.3/9.3.9/bin I can see there is postgres.

Not sure how to approach the problem.
Thanks in advance.

**Comment by petere** [comment]
This is a new variation of this problem, because the `openldap` formula is now keg-only (Homebrew/homebrew-dupes#492).  I'll see about fixing this.

**Comment by joaoponceleao** [comment]
In the meanwhile, would there be any caveats in doing a simple `brew link openldap --force`? It seems to take care of the problem (and does it need to be a permanent link, or just temporary for the build process?).

**Comment by petere** [comment]
You can either force-link openldap and leave it there until the bottles are fixed, or install from source, which will find openldap in its new location.

**Comment by maxlipsky** [comment]
@joaoponceleao Thank, `brew link openldap --force` working for me (OS X 10.10.2).
