### ISSUE TITLE
Upgrading from "normal" brew postgresql to this?

### ISSUE THREAD

**Issue by pjammer** [petere/homebrew-postgresql#23]
I'm not grokking something. I have `9.3.5_1` installed and now want `9.4.x`.

``` bash
> brew info postgresql
postgresql: stable 9.5.2 (bottled)
Object-relational database system
https://www.postgresql.org/
Conflicts with: postgres-xc
/usr/local/Cellar/postgresql/9.3.5_1 (2,936 files, 32.1M) *
  Built from source
/usr/local/Cellar/postgresql/9.4.4 (3,023 files, 33.5M)
  Poured from bottle

> psql --version
psql (PostgreSQL) 9.3.5

```

How does one upgrade?  Or maybe i'm going about this approach wrong. If i need one database on 9.4, do I just 'somehow' get the data directory somewhere and reference that from the startup script for 9.4 then dump the database i want into that new directory?  I'm open for any ideas too, but just am unclear as to whether the lack of upgrade documentation is due to the fact you don't upgrade, but just "put another PG on your system, and use that one instead"? Not sure where else to turn to ask this kind of question so thanks!

**Comment by petere** [comment]
If you have `postgresql-common` installed, you can use `pg_upgradecluster` to upgrade between different instances. But to do what you are describing you need to run `pg_upgrade` or `pg_dumpall` and restore yourself.
