### ISSUE TITLE
Add PostGIS to the repo

### ISSUE THREAD

**Issue by jmagnusson** [petere/homebrew-postgresql#24]
As it's so widely used it could be nice to have a historical archive of PostGIS versions in this repo. The ones in homebrew / homebrew-versions are all tied to the standard postgresql versions and it's hard to mix them. I've personally not been able to set up multiple postgis versions with homebrew.

**Comment by petere** [comment]
My preferred solution for this is using [pex](https://github.com/petere/pex).

**Comment by jmagnusson** [comment]
Thanks, looking into it now 😊

**Comment by jmagnusson** [comment]
Thanks, looking into it now 😊

**Comment by HackerMD** [comment]
When running `pex -g /usr/local/opt/postgresql-9.6 install postgis` I get the following error:

```
    In file included from /usr/local/Cellar/postgresql-9.6/9.6.0/include/server/postgres.h:47:
/usr/local/Cellar/postgresql-9.6/9.6.0/include/server/c.h:123:10: fatal error: 'libintl.h' file not found
#include <libintl.h>
         ^
1 error generated.
```

**Comment by jmagnusson** [comment]
@HackerMD Your issue is described here: https://github.com/petere/pex/issues/4

**Comment by HackerMD** [comment]
Sweet! Linking `brew link -f gettext` solved the issue. Thank's!

**Comment by ndbroadbent** [comment]
Sorry to comment on an old thread, but I'm having a hard time installing the PostGIS extension for postgres 11. I think it would be really useful if a precompiled PostGIS extension was available in the repo, and maybe some other popular postgres extensions. Or maybe some instructions for how to install PostGIS without needing to compile.

I ran into a lot of different issues. In case anyone else finds this, here's everything I needed to run in order to install PostGIS for Postgres 11 on an up-to-date Mac (macOS Monterey) with recent Homebrew packages:

```bash
# We need proj 7 (brew installs proj 9)
brew install proj@7

# Need gettext
brew install gettext

# Requires a slightly older version of libtiff, can be fixed with a symlink
if ! [ -e /usr/local/Cellar/libtiff/4.3.0 ]; then 
  ln -fs /usr/local/Cellar/libtiff/4.4.0 /usr/local/Cellar/libtiff/4.3.0
fi

# Need to tell the compiler where to find proj and gettext:
export LDFLAGS="-L/usr/local/opt/proj@7/lib -L/usr/local/Cellar/gettext/0.21/lib"
export CPPFLAGS="-I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/"

# Install the postgis extension into the Postgres 11 directory
pex -g /usr/local/opt/postgresql@11 install postgis
```

----------

Wrong version of `proj` (brew installs 9 by default, but `proj@7` is also available.) Fixed with `CPPFLAGS`:

```
export LDFLAGS="-L/usr/local/opt/proj@7/lib"
export CPPFLAGS="-I/usr/local/opt/proj@7/include"
```

Missing `libintl.h` error. A lot of StackOverflow answers suggested running these commands to fix `gettext`, but they didn't help:

```
brew reinstall gettext
brew unlink gettext && brew link gettext --force
```

Finally fixed it by finding the location of `libintl.h`:

```
$ find /usr/local -name "libintl.*" -print
/usr/local/include/libintl.h
/usr/local/lib/libintl.dylib
/usr/local/lib/libintl.8.dylib
/usr/local/lib/libintl.a
/usr/local/Cellar/gawk/5.1.1/share/awk/libintl.awk
/usr/local/Cellar/gettext/0.21/include/libintl.h
/usr/local/Cellar/gettext/0.21/lib/libintl.dylib
/usr/local/Cellar/gettext/0.21/lib/libintl.8.dylib
/usr/local/Cellar/gettext/0.21/lib/libintl.a
```

Then set `CPPFLAGS`:

```
export CPPFLAGS="-I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/"
```

Then a weird `libtiff` error: 

```
ld: warning: directory not found for option '-L/usr/local/Cellar/libtiff/4.3.0/lib'
ld: library not found for -ltiff
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [shp2pgsql] Error 1
make: *** [all] Error 1
```

It looks like it's trying to use two different versions of libtiff:

```
libtool: link: gcc -I ../liblwgeom -I/usr/local/Cellar/geos/3.10.3/include -I/usr/local/Cellar/proj/9.0.1/include -I/usr/local/Cellar/libtiff/4.4.0_1/include -I/usr/local/Cellar/protobuf-c/1.4.0_1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/usr/local/Cellar/sfcgal/1.4.1_1/include -I/usr/local/Cellar/json-c/0.16/include -I/usr/local/Cellar/json-c/0.16/include/json-c -I/usr/local/Cellar/pcre/8.45/include -DNDEBUG -I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/ -std=gnu99 -g -O2 -fno-math-errno -fno-signed-zeros -fno-common -DPIC -I/usr/local/Cellar/proj/9.0.1/include -I/usr/local/Cellar/libtiff/4.4.0_1/include shpopen.o dbfopen.o getopt.o shpcommon.o safileio.o shp2pgsql-core.o shp2pgsql-cli.o -o shp2pgsql -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wl,-dead_strip_dylibs -Wl,-framework -Wl,CoreFoundation  -L/usr/local/opt/postgresql@11/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib ../liblwgeom/.libs/liblwgeom.a -L/usr/local/opt/proj@7/lib -L/usr/local/Cellar/geos/3.10.3/lib -lgeos_c -L/usr/local/Cellar/proj/9.0.1/lib /usr/local/Cellar/proj@7/7.2.1/lib/libproj.dylib -lsqlite3 -L/usr/local/Cellar/libtiff/4.3.0/lib -ltiff -lcurl -lpthread -ldl -lm -L/usr/local/Cellar/json-c/0.16/lib -ljson-c -L/usr/local/Cellar/sfcgal/1.4.1_1/lib -lSFCGAL -lintl -liconv
```

* `-I/usr/local/Cellar/libtiff/4.4.0_1/include`
* `-L/usr/local/Cellar/libtiff/4.3.0/lib`

Attempted to fix it with a symlink from 4.4.0 => 4.3.0, which seemed to work:

```
$ ln -fs /usr/local/Cellar/libtiff/4.4.0 /usr/local/Cellar/libtiff/4.3.0
$ ls -l /usr/local/Cellar/libtiff/
total 0
lrwxr-xr-x  1 ndbroadbent staff  31 Aug 11 14:28 4.3.0 -> /usr/local/Cellar/libtiff/4.4.0
drwxr-xr-x 12 ndbroadbent staff 384 Aug 11 14:28 4.4.0
drwxr-xr-x 12 ndbroadbent staff 384 Aug  5 14:02 4.4.0_1
```

Then `ld: library not found for -lintl`:

```
libtool: link: gcc -I ../liblwgeom -I/usr/local/Cellar/geos/3.10.3/include -I/usr/local/Cellar/proj/9.0.1/include -I/usr/local/Cellar/libtiff/4.4.0_1/include -I/usr/local/Cellar/protobuf-c/1.4.0_1/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/usr/local/Cellar/sfcgal/1.4.1_1/include -I/usr/local/Cellar/json-c/0.16/include -I/usr/local/Cellar/json-c/0.16/include/json-c -I/usr/local/Cellar/pcre/8.45/include -DNDEBUG -I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/ -std=gnu99 -g -O2 -fno-math-errno -fno-signed-zeros -fno-common -DPIC -I/usr/local/Cellar/proj/9.0.1/include -I/usr/local/Cellar/libtiff/4.4.0_1/include shpopen.o dbfopen.o getopt.o shpcommon.o safileio.o shp2pgsql-core.o shp2pgsql-cli.o -o shp2pgsql -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -Wl,-dead_strip_dylibs -Wl,-framework -Wl,CoreFoundation  -L/usr/local/opt/postgresql@11/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib ../liblwgeom/.libs/liblwgeom.a -L/usr/local/opt/proj@7/lib -L/usr/local/Cellar/geos/3.10.3/lib -lgeos_c -L/usr/local/Cellar/proj/9.0.1/lib /usr/local/Cellar/proj@7/7.2.1/lib/libproj.dylib -lsqlite3 -L/usr/local/Cellar/libtiff/4.3.0/lib -ltiff -lcurl -lpthread -ldl -lm -L/usr/local/Cellar/json-c/0.16/lib -ljson-c -L/usr/local/Cellar/sfcgal/1.4.1_1/lib -lSFCGAL -lintl -liconv
ld: library not found for -lintl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [shp2pgsql] Error 1
make: *** [all] Error 1
```

I had forgotten to add `-L/usr/local/Cellar/gettext/0.21/lib` to `LDFLAGS`:

```
export LDFLAGS="-L/usr/local/opt/proj@7/lib -L/usr/local/Cellar/gettext/0.21/lib"
export CPPFLAGS="-I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/"
```

Then it finally worked, and I was able to create the `postgis` extension.

```
==> Package postgis installed successfully
```

```
postgres=# CREATE EXTENSION postgis;
CREATE EXTENSION
postgres=# \dx
                                List of installed extensions
  Name   | Version |   Schema   |                        Description
---------+---------+------------+------------------------------------------------------------
 plpgsql | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgis | 3.1.1   | public     | PostGIS geometry and geography spatial types and functions
(2 rows)

postgres=#
```

Would be nice if this could be a little bit easier. I don't know if it's possible to provide some pre-compiled extensions (or download them from an old homebrew revision?) Or maybe use the Nix package manager if users need to compile it.

Anyway, hope this helps someone!

**Comment by tflambre-fairville** [comment]
> 
> Missing `libintl.h` error. A lot of StackOverflow answers suggested running these commands to fix `gettext`, but they didn't help:
> 
> ```
> brew reinstall gettext
> brew unlink gettext && brew link gettext --force
> ```
> 
> Finally fixed it by finding the location of `libintl.h`:
> 
> ```
> $ find /usr/local -name "libintl.*" -print
> /usr/local/include/libintl.h
> /usr/local/lib/libintl.dylib
> /usr/local/lib/libintl.8.dylib
> /usr/local/lib/libintl.a
> /usr/local/Cellar/gawk/5.1.1/share/awk/libintl.awk
> /usr/local/Cellar/gettext/0.21/include/libintl.h
> /usr/local/Cellar/gettext/0.21/lib/libintl.dylib
> /usr/local/Cellar/gettext/0.21/lib/libintl.8.dylib
> /usr/local/Cellar/gettext/0.21/lib/libintl.a
> ```
> 
> Then set `CPPFLAGS`:
> 
> ```
> export CPPFLAGS="-I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/"
> ```
> 

I fixed this by copying the libintl.h file to the directory from the script where it was missing and then changing 

#include <libintl.h>
to
#include "libintl.h"

**Comment by amitsaxena** [comment]
> > Missing `libintl.h` error. A lot of StackOverflow answers suggested running these commands to fix `gettext`, but they didn't help:
> > ```
> > brew reinstall gettext
> > brew unlink gettext && brew link gettext --force
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Finally fixed it by finding the location of `libintl.h`:
> > ```
> > $ find /usr/local -name "libintl.*" -print
> > /usr/local/include/libintl.h
> > /usr/local/lib/libintl.dylib
> > /usr/local/lib/libintl.8.dylib
> > /usr/local/lib/libintl.a
> > /usr/local/Cellar/gawk/5.1.1/share/awk/libintl.awk
> > /usr/local/Cellar/gettext/0.21/include/libintl.h
> > /usr/local/Cellar/gettext/0.21/lib/libintl.dylib
> > /usr/local/Cellar/gettext/0.21/lib/libintl.8.dylib
> > /usr/local/Cellar/gettext/0.21/lib/libintl.a
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then set `CPPFLAGS`:
> > ```
> > export CPPFLAGS="-I/usr/local/opt/proj@7/include -I/usr/local/Cellar/gettext/0.21/include/"
> > ```
> 
> I fixed this by copying the libintl.h file to the directory from the script where it was missing and then changing
> 
> #include <libintl.h> to #include "libintl.h"

For ARM based Macs the directory structure is different:
```
$ find /opt -name "libintl.*" -print
/opt/homebrew/include/libintl.h
/opt/homebrew/lib/libintl.dylib
/opt/homebrew/lib/libintl.8.dylib
/opt/homebrew/lib/libintl.a
/opt/homebrew/Cellar/gettext/0.22.5/include/libintl.h
/opt/homebrew/Cellar/gettext/0.22.5/lib/libintl.dylib
/opt/homebrew/Cellar/gettext/0.22.5/lib/libintl.8.dylib
/opt/homebrew/Cellar/gettext/0.22.5/lib/libintl.a
```

So the exports should look different:
```
export CPPFLAGS="-I/opt/homebrew/opt/gettext/include"
export LDFLAGS="-L/opt/homebrew/opt/gettext/lib"
```

So either use the exports above or change the configure command to this:
```
./configure --with-projdir=/opt/homebrew/opt/proj --with-protobufdir=/opt/homebrew/opt/protobuf-c --with-pgconfig=/opt/homebrew/opt/postgresql@15/bin/pg_config --with-jsondir=/opt/homebrew/opt/json-c "LDFLAGS=$LDFLAGS -L/opt/homebrew/Cellar/gettext/0.21.1/lib -L/opt/homebrew/opt/gettext/lib" "CFLAGS=-I/opt/homebrew/Cellar/gettext/0.21.1/include" CPPFLAGS="-I/opt/homebrew/opt/gettext/include"

make
make install
```
