### ISSUE TITLE
Error: SHA256 mismatch tcl-tk--tcllib-1.17.tar.gz for Postgresql 9.5

### ISSUE THREAD

**Issue by tvmaly** [petere/homebrew-postgresql#25]
==> Downloading from https://codeload.github.com/tcltk/tcllib/tar.gz/tcllib_1_17
###### ################################################################## 100.0%

Error: SHA256 mismatch
Expected: 1653165693125e86e8b77929c22210fb50a9b46271c321ac292cd5497cdde2d2
Actual: 95c676130ce2fdb00e8a6f79c4fea9e79d071063783a61db9274647920d97a03
Archive: /Library/Caches/Homebrew/tcl-tk--tcllib-1.17.tar.gz
To retry an incomplete download, remove the file above.

I tried deleting the cached file and re-running the install but it gives the same error.

Does the hash need to be updated or is there a different problem?

**Comment by petere** [comment]
This may be a problem in the `tcl-tk` formula, in which case the issue should be reported there.

**Comment by yas375** [comment]
I'm getting similar problem but with tcllib 1.18 when trying to install postgresql 9.1

```sh
➜  ~  brew tap petere/postgresql
➜  ~  brew install postgresql-9.1
==> Installing postgresql-9.1 from petere/postgresql
==> Installing dependencies for petere/postgresql/postgresql-9.1: homebrew/dupes/tcl-tk
==> Installing petere/postgresql/postgresql-9.1 dependency: homebrew/dupes/tcl-tk
==> Using the sandbox
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.6/tcl8.6.6-src.tar.gz
Already downloaded: /Users/yas/Library/Caches/Homebrew/tcl-tk-8.6.6.tar.gz
==> ./configure --prefix=/usr/local/Cellar/tcl-tk/8.6.6 --mandir=/usr/local/Cellar/tcl-tk/8.6.6/share/man --enable-64bit
==> make
==> make install
==> make install-private-headers
==> Downloading https://downloads.sourceforge.net/project/tcl/Tcl/8.6.6/tk8.6.6-src.tar.gz
Already downloaded: /Users/yas/Library/Caches/Homebrew/tcl-tk--tk-8.6.6.tar.gz
==> ./configure --prefix=/usr/local/Cellar/tcl-tk/8.6.6 --mandir=/usr/local/Cellar/tcl-tk/8.6.6/share/man --with-tcl=/usr/local/Cellar/tcl-tk
==> make TK_LIBRARY=/usr/local/Cellar/tcl-tk/8.6.6/lib
==> make install
==> make install-private-headers
==> Downloading https://github.com/tcltk/tcllib/archive/tcllib_1_18.tar.gz
Already downloaded: /Users/yas/Library/Caches/Homebrew/tcl-tk--tcllib-1.18.tar.gz
Error: SHA256 mismatch
Expected: bcf0ba7656e3a99ffa5fc0ce0f4a95616530979539bddb8da43903b82983603f
Actual: 6a87881f545afb69c1130f60984b5d35cc22f1593b0835b982871c188fde3de8
Archive: /Users/yas/Library/Caches/Homebrew/tcl-tk--tcllib-1.18.tar.gz
To retry an incomplete download, remove the file above.
➜  ~
```

I wasn't sure what to do and how to fix and found this issue. Do you think the problem can be similar to https://github.com/Homebrew/homebrew-dupes/pull/512 and should be fixed by updating [this line](https://github.com/Homebrew/homebrew-dupes/blob/5c83c93d3df0b105cc576680254c23cc69a275da/tcl-tk.rb#L34)? By any change someone can suggest how I can verify it locally before submitting a PR there?

**Comment by yas375** [comment]
Ended up by copying the content of that formula into a gist, fixing SHA there and installing from the gist. It did work!
Also have submitted a PR there: https://github.com/Homebrew/homebrew-dupes/pull/659
