### ISSUE TITLE
wrapper scripts using wrong path

### ISSUE THREAD

**Issue by paul** [petere/homebrew-postgresql#31]
On a fresh install today, I've been running into lots of troubles getting the pg_common tools to work.

In `pg_createcluster`, I got the error `Error: no initdb program for version 9.6 found` until I modified PgCommon.pm:

```perl
$binroot = "/usr/local/opt/postgresql@";
$binroot = "/usr/local/opt/postgresql-";
```

Additionally, I was unable to install the `pg` Rubygem because `pg_config` also failed with an error: 

```
$ pg_config
You need to install postgresql@X.Y for building a server-side extension or a client-side application.
```

I had to modify it similarly:

```bash
PGBINROOT="/usr/local/opt/postgresql@"
PGBINROOT="/usr/local/opt/postgresql-"
```

When I install `postgresql-9.6` via this homebrew formula, it ends up installing it in `/usr/local/opst/postgresql-9.2`, with a `-`, not a `@` as the scripts seem to expect.

```
$ ls -l /usr/local/opt/postgresql*
lrwxr-xr-x 1 rando admin 30 Apr  2 17:50 /usr/local/opt/postgresql-9.6 -> ../Cellar/postgresql-9.6/9.6.2/
lrwxr-xr-x 1 rando admin 40 Apr  2 17:35 /usr/local/opt/postgresql-common -> ../Cellar/postgresql-common/HEAD-74c810d/
```

Perhaps something changed upstream that needs to be patched? I'm not very familiar with the postgresql-common tool itself from debian...

Thanks!

**Comment by paul** [comment]
Another one: I had to modify `PgCommon.pm` line 660 with the same `@`/`-` change to get `pg_dump` etc to work:

```perl
            $pfx = "postgresql-";
```

**Comment by doredesign** [comment]
@petere When do you think you'll get the version-renaming branch merged to master?

**Comment by petere** [comment]
Recently, the versioned formulas were renamed `postgresql-9.6` -> `postgresql@9.6` etc. So you need to upgrade all the formulas as well as `postgresql-common` together.

**Comment by paul** [comment]
Updating everything all at once seems to have solved it. I must have done the initial install at a weird time. Thanks!
