### ISSUE TITLE
pg-common tools can't find postgresql@10 path

### ISSUE THREAD

**Issue by paul** [petere/homebrew-postgresql#35]
First of all, thank you for all your hard work with this project, I really appreciate it.

I wanted to try out the postgresql 10 beta, and installed it. However, the pg_createcluster tools can't seem to find it because of the version number. Probably best shown with an example:

```
$ pg_createcluster -p 54100 10 main
Error: invalid version '10'

$ pg_createcluster -p 54100 10.0 main
Error: no initdb program for version 10.0 found
path: /usr/local/opt/postgresql@10.0/bin/initdb% # I modified PgCommon.pm to print the path

$ ls /usr/local/opt/postgresql*
/usr/local/opt/postgresql-common@
'/usr/local/opt/postgresql@10'@
'/usr/local/opt/postgresql@9.4'@
```

Apparently the pg_createcluster tool expects versions like `X.Y`, so just `10` doesn't work. However, the `postgresql@10` package installs to just the major version, so pg_createcluster can't find it.

I was able to solve this by symlinking:

```
$ ln -s /usr/local/opt/postgresql@10 /usr/local/opt/postgresql@10.0
```

Perhaps the formula should install to `postgresql@10.0` by default?

Thanks!

**Comment by pjungwir** [comment]
I'm having this same problem, despite being on postgresql-common 179+hb1. Looking at eb5e622, I don't see how it would fix this problem. So maybe it's still an issue?

**Comment by scmx** [comment]
Also having this problem
