### ISSUE TITLE
postgresql@10 does not install.

### ISSUE THREAD

**Issue by webervin** [petere/homebrew-postgresql#38]
```
09:21 $ brew list | grep  postgresql
postgresql-common
postgresql@10
postgresql@9.6
09:21 $ which initdb
/Users/me/tools/brew/Cellar/postgresql@10/10.0/bin/initdb
09:21 $ pg_createcluster 10.0 main
Error: no initdb program for version 10.0 found
```

seems you own test fails for said version also, but with different message: https://travis-ci.org/petere/homebrew-postgresql/jobs/283741183

**Comment by webervin** [comment]
seems that this is due to https://github.com/petere/postgresql-common being version 165, but support for PostgreSQL 10 was added in 176 (see [changelog](http://metadata.ftp-master.debian.org/changelogs/main/p/postgresql-common/postgresql-common_186_changelog) )

**Comment by petere** [comment]
There is a mistake in your command. You need to write

    pg_createcluster 10 main

This works with current `postgresql-common`.
