### ISSUE TITLE
Fully qualified name petere/postgresql/postgresql@10 is needed to install correct formula

### ISSUE THREAD

**Issue by scmx** [petere/homebrew-postgresql#40]
Hey, I noticed a while ago that `brew install postgresql@10` doesn't use the formula from this tap, but instead installs the core `postgresql` formula. However when using `brew install postgresql@9.6` I do get a package from this tap 🤔 .

A workaround is to specify the fully qualified name `brew install petere/postgresql/postgresql@10` or use `brew tap-pin petere/postgresql`.

There's documentation about formula name collisions here https://docs.brew.sh/Taps#formula-duplicate-names

Some ideas for how to make this clearer in the README:
- Suggest `brew install petere/postgresql/<formula>` instead of `brew install <formula>`
- Or suggest `brew tap-pin petere/postgresql` instead
- Do you want a pull request?

Here's how to reproduce it:

<details open>
<summary><code>brew tap petere/postgresql</code></summary>
</details>

<details open>
<summary><code>brew install postgresql-common</code></summary>
</details>

<details>
<summary><code>brew install postgresql@9.6</code></summary>

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).

==> Downloading https://homebrew.bintray.com/bottles/postgresql@9.6-9.6.9.high_sierra.bottle.tar.gz
Already downloaded: /Users/albert/Library/Caches/Homebrew/postgresql@9.6-9.6.9.high_sierra.bottle.tar.gz
==> Pouring postgresql@9.6-9.6.9.high_sierra.bottle.tar.gz
==> Caveats
If builds of PostgreSQL 9 are failing and you have version 8.x installed,
you may need to remove the previous version first. See:
  https://github.com/Homebrew/legacy-homebrew/issues/2510

To migrate existing data from a previous major version (pre-9.0) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/upgrading.html

To migrate existing data from a previous minor version (9.0-9.5) of PostgreSQL, see:
  https://www.postgresql.org/docs/9.6/static/pgupgrade.html

  You will need your previous PostgreSQL installation from brew to perform `pg_upgrade`.
    Do not run `brew cleanup postgresql@9.6` until you have performed the migration.

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/postgresql@9.6/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/postgresql@9.6/lib
    CPPFLAGS: -I/usr/local/opt/postgresql@9.6/include

To have launchd start postgresql@9.6 now and restart at login:
  brew services start postgresql@9.6
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgresql@9.6 start
==> Summary
🍺  /usr/local/Cellar/postgresql@9.6/9.6.9: 3,287 files, 37.0MB

</details>

<details>
<summary><strong><code>brew install postgresql@10</code> ⚠️  </strong></summary>

==> Downloading https://homebrew.bintray.com/bottles/postgresql-10.4.high_sierra.bottle.tar.gz
Already downloaded: /Users/albert/Library/Caches/Homebrew/postgresql-10.4.high_sierra.bottle.tar.gz
==> Pouring postgresql-10.4.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/clusterdb
Target /usr/local/bin/clusterdb
is a symlink belonging to postgresql-common. You can unlink it:
  brew unlink postgresql-common

To force the link and overwrite all conflicting files:
  brew link --overwrite postgresql

To list all files that would be deleted:
  brew link --overwrite --dry-run postgresql

Possible conflicting files are:
/usr/local/bin/clusterdb -> /usr/local/Cellar/postgresql-common/189+hb1/bin/clusterdb
/usr/local/bin/createdb -> /usr/local/Cellar/postgresql-common/189+hb1/bin/createdb
/usr/local/bin/createuser -> /usr/local/Cellar/postgresql-common/189+hb1/bin/createuser
/usr/local/bin/dropdb -> /usr/local/Cellar/postgresql-common/189+hb1/bin/dropdb
/usr/local/bin/dropuser -> /usr/local/Cellar/postgresql-common/189+hb1/bin/dropuser
/usr/local/bin/pg_basebackup -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pg_basebackup
/usr/local/bin/pg_config -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pg_config
/usr/local/bin/pg_dump -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pg_dump
/usr/local/bin/pg_dumpall -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pg_dumpall
/usr/local/bin/pg_isready -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pg_isready
/usr/local/bin/pg_restore -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pg_restore
/usr/local/bin/pgbench -> /usr/local/Cellar/postgresql-common/189+hb1/bin/pgbench
/usr/local/bin/psql -> /usr/local/Cellar/postgresql-common/189+hb1/bin/psql
/usr/local/bin/reindexdb -> /usr/local/Cellar/postgresql-common/189+hb1/bin/reindexdb
/usr/local/bin/vacuumdb -> /usr/local/Cellar/postgresql-common/189+hb1/bin/vacuumdb
/usr/local/bin/vacuumlo -> /usr/local/Cellar/postgresql-common/189+hb1/bin/vacuumlo
==> /usr/local/Cellar/postgresql/10.4/bin/initdb /usr/local/var/postgres
Last 15 lines from /Users/albert/Library/Logs/Homebrew/postgresql/post_install.01.initdb:
2018-06-21 15:22:19 +0200

/usr/local/Cellar/postgresql/10.4/bin/initdb
/usr/local/var/postgres

The files belonging to this database system will be owned by user "albert".
This user must also own the server process.

initdb: file "/usr/local/share/postgresql/postgres.bki" does not exist
This might mean you have a corrupted installation or identified
the wrong directory with the invocation option -L.
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall postgresql`
==> Caveats
To migrate existing data from a previous major version of PostgreSQL run:
  brew postgresql-upgrade-database

To have launchd start postgresql now and restart at login:
  brew services start postgresql
Or, if you don't want/need a background service you can just run:
  pg_ctl -D /usr/local/var/postgres start
==> Summary
🍺  /usr/local/Cellar/postgresql/10.4: 3,389 files, 39.2MB
</details>

<details open>
<summary><code>brew list | grep postgresql</code></summary>

  - postgresql ⚠️ 
  - postgresql-common
  - postgresql@9.6

</details>

<details>
<summary><code>pg_createcluster 9.6 pg9</code></summary>

Creating new PostgreSQL cluster 9.6/pg9 ...
/usr/local/opt/postgresql@9.6/bin/initdb -D /usr/local/var/lib/postgresql/9.6/pg9 --auth-local peer --auth-host md5
The files belonging to this database system will be owned by user "albert".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /usr/local/var/lib/postgresql/9.6/pg9 ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

Success. You can now start the database server using:

    /usr/local/opt/postgresql@9.6/bin/pg_ctl -D /usr/local/var/lib/postgresql/9.6/pg9 -l logfile start

Ver Cluster Port Status Owner  Data directory                        Log file
9.6 pg9     5432 down   albert /usr/local/var/lib/postgresql/9.6/pg9 /usr/local/var/log/postgresql/postgresql-9.6-pg9.log

</details>

<details open>
<summary><strong><code>pg_createcluster 10 pg10</code> 💥 </strong></summary>

Creating new PostgreSQL cluster 10/pg10 ...
/usr/local/opt/postgresql@10/bin/initdb -D /usr/local/var/lib/postgresql/10/pg10 --auth-local peer --auth-host md5
The files belonging to this database system will be owned by user "albert".
This user must also own the server process.

initdb: file "/usr/local/share/postgresql/postgres.bki" does not exist
This might mean you have a corrupted installation or identified
the wrong directory with the invocation option -L.
Error: initdb failed

</details>

<details open>
<summary><code>brew uninstall postgresql@10</code></summary>
</details>

<details>
<summary><code>brew install petere/postgresql/postgresql@10</code></summary>

==> Installing postgresql@10 from petere/postgresql
==> Installing dependencies for petere/postgresql/postgresql@10: pkg-config, e2fsprogs, openldap, icu4c, tcl-tk
==> Installing petere/postgresql/postgresql@10 dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/f1/f1b29fb5388dccab0fcaf665ab43d308ee51816b24262417bf83a686b6e308ae?__gda__=exp=1529588096~hmac=b9f7a43457a1228
######################################################################## 100.0%
==> Pouring pkg-config-0.29.2.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2: 11 files, 627.2KB
==> Installing petere/postgresql/postgresql@10 dependency: e2fsprogs
==> Downloading https://homebrew.bintray.com/bottles/e2fsprogs-1.44.2.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/85/85d5829a6e42d07b909db8341cc5c1cc38c2a1cd27f7cc3574195755e567a786?__gda__=exp=1529588097~hmac=237f4781160179e
######################################################################## 100.0%
==> Pouring e2fsprogs-1.44.2.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because this installs several executables which shadow macOS system commands.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/e2fsprogs/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/e2fsprogs/sbin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/e2fsprogs/lib
    CPPFLAGS: -I/usr/local/opt/e2fsprogs/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/e2fsprogs/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/e2fsprogs/1.44.2: 138 files, 6.9MB
==> Installing petere/postgresql/postgresql@10 dependency: openldap
==> Downloading https://homebrew.bintray.com/bottles/openldap-2.4.46.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/20/2094541bf0f0b265e6cc1518aa5ac223b75834f0aa12bec8e00b6c9469e9b5d9?__gda__=exp=1529588098~hmac=1ffea85f19ee33c
######################################################################## 100.0%
==> Pouring openldap-2.4.46.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/openldap/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/openldap/sbin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openldap/lib
    CPPFLAGS: -I/usr/local/opt/openldap/include

==> Summary
🍺  /usr/local/Cellar/openldap/2.4.46: 327 files, 6.6MB
==> Installing petere/postgresql/postgresql@10 dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-61.1.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/be/be8b3ba9420c4da1a75b2e6ebb7a0b835e2919d6499216383f0f313b1d9bb26b?__gda__=exp=1529588100~hmac=4a655c8952c263c
######################################################################## 100.0%
==> Pouring icu4c-61.1.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.zshrc
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/icu4c/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/icu4c/61.1: 249 files, 67.2MB
==> Installing petere/postgresql/postgresql@10 dependency: tcl-tk
==> Downloading https://homebrew.bintray.com/bottles/tcl-tk-8.6.8.high_sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/cd/cd4dec2b564dcad86b151803c852142366bc48ec1b13d48a2e495c83fc32a688?__gda__=exp=1529588105~hmac=e1e6abbf9af7be2
######################################################################## 100.0%
==> Pouring tcl-tk-8.6.8.high_sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because tk installs some X11 headers and macOS provides an (older) Tcl/Tk.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/tcl-tk/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/tcl-tk/lib
    CPPFLAGS: -I/usr/local/opt/tcl-tk/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/tcl-tk/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/tcl-tk/8.6.8: 2,849 files, 29.2MB
==> Installing petere/postgresql/postgresql@10
==> Downloading https://ftp.postgresql.org/pub/source/v10.4/postgresql-10.4.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/postgresql@10/10.4 --enable-dtrace --enable-nls --with-bonjour --with-gssapi --with-icu --with-ldap --with-libxml --
==> make install-world
==> Caveats
To use this PostgreSQL installation, do one or more of the following:

- Call all programs explicitly with /usr/local/opt/postgresql@10/bin/...
- Add /usr/local/opt/postgresql@10/bin to your PATH
- brew link -f postgresql@10
- Install the postgresql-common package

To access the man pages, do one or more of the following:
- Refer to them by their full path, like `man /usr/local/opt/postgresql@10/share/man/man1/psql.1`
- Add /usr/local/opt/postgresql@10/share/man to your MANPATH
- brew link -f postgresql@10

This formula is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/postgresql@10/bin:$PATH"' >> ~/.zshrc

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/postgresql@10/lib
    CPPFLAGS: -I/usr/local/opt/postgresql@10/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/postgresql@10/lib/pkgconfig

==> Summary
🍺  /usr/local/Cellar/postgresql@10/10.4: 3,690 files, 51.8MB, built in 3 minutes 10 seconds

</details>

<details open>
<summary><code>brew list | grep postgresql</code></summary>

  - postgresql-common
  - postgresql@10 💆‍♂️ 
  - postgresql@9.6

</details>

**Comment by jasonmp85** [comment]
Hey @scmx; random question: How did you do the `details`/`summary` stuff? Is there a GFM syntax for it, or did you type the HTML directly?

**Comment by jasonmp85** [comment]
(Also, what's wrong with using pinning? I don't consider this a workaround… I think it's the right solution here. Given that, can this issue be closed?)

**Comment by scmx** [comment]
Opened a PR for this now.

---

@jasonmp85 regarding `details` / `summary`, I typed it directly. Here's a gist about it: https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2
