### ISSUE TITLE
Support for multiple @10 minor versions?

### ISSUE THREAD

**Issue by justindoody** [petere/homebrew-postgresql#42]
Am I missing something or is this just not supported like it is for 9.x version? If so am curious why?

**Comment by petere** [comment]
9.x were different _major_ versions. The version numbering was changed with version 10. These packages never supported different _minor_ versions like 9.5.1 vs 9.5.2.

See https://www.postgresql.org/support/versioning/.

**Comment by justindoody** [comment]
got it -- thanks!
