### ISSUE TITLE
@ sign creates issues in $PATH

### ISSUE THREAD

**Issue by daBee** [petere/homebrew-postgresql#47]
Trying to get my 10.6 fixed again, I've found some feedback that the posix `postgresql@10` has been rewritten or suggested to be `postgresql\@10`.  Might want to start using an underscore for that to avoid the sheer confusion of not finding `pg_ctl` due to that.  FYI

**Comment by petere** [comment]
This report is not very useful. What were you doing, and what happened, and what did you expect to happen instead?

**Comment by daBee** [comment]
That was over a month ago.  I can't remember last week.  I remember seeing something trip over the @ sign, and paths have been an issue with `10.6` and `10.6_1` due to the installation.  The first I don't recall for the most part and the second one I've submitted as its own report somewhere, which is now closed as it repaired itself after a reinstall somehow.
