### ISSUE TITLE
Server version mismatch with Postgresql tools

### ISSUE THREAD

**Issue by ogirginc** [petere/homebrew-postgresql#54]
If this isn't the place to ask, sorry for taking your time! I am getting the error below when I use `psql`

```
psql (10.11 (Homebrew petere/postgresql), server 11.6 (Homebrew petere/postgresql))
```

It wasn't an issue until I tried to use `pg_dumpall`. When I run

```
pg_dumpall > ~/Downloads/all_databases.sql
```

I got the error below:

```
server version: 11.6 (Homebrew petere/postgresql); pg_dumpall version: 10.11 (Homebrew petere/postgresql)
aborting because of server version mismatch
```

It's not a deal breaker as I can simply use

```
/usr/local/Cellar/postgresql@11/11.6/bin/pg_dumpall > ~/Downloads/all_databases.sql
```

However, my assumption was this shouldn't be a problem at all because, even though I have multiple Postgresql installed, I am only running v11.

```
$ pg_lsclusters
Ver Cluster Port Status Owner    Data directory                        Log file
11  main    5432 online ogirginc /usr/local/var/lib/postgresql/11/main /usr/local/var/log/postgresql/postgresql-11-main.log
```

I would like to know if it is possible to force `psql` or any other Postgresql tool to use the same version as the Postgresql version? Or am I misunderstanding the use of clusters?

### Setup

- macOS Catalina 10.15.2
- postgresql-common
```
$ brew info petere/postgresql/postgresql-common
petere/postgresql/postgresql-common: stable 189+hb1, HEAD
PostgreSQL database-cluster manager
https://packages.qa.debian.org/p/postgresql-common.html
Conflicts with:
  postgresql (because both install the same binaries.)
/usr/local/Cellar/postgresql-common/189+hb1 (45 files, 244KB) *
  Built from source on 2020-01-30 at 11:22:18
From: https://github.com/petere/homebrew-postgresql/blob/master/postgresql-common.rb
==> Dependencies
Build: gnu-sed ✔
Required: coreutils ✔
==> Options
--HEAD
	Install HEAD version
```

**Comment by petere** [comment]
The `pg_wrapper(1)` man page explains how the version of the client program is chosen. Please check how that applies to your situation.

**Comment by ogirginc** [comment]
From what I have [read](https://www.mankier.com/1/pg_wrapper), `PGCLUSTER="12/main" psql` should have work but it didn't. So, I asked it on [Stackoverflow](https://stackoverflow.com/questions/61312380/how-to-specify-postgresql-client-version-to-prevent-server-version-mismatch) too.
