### ISSUE TITLE
configure: error: Cannot find a working 64-bit integer type.

### ISSUE THREAD

**Issue by frankhuster** [petere/homebrew-postgresql#56]
On Catalina 10.15.7, running

`brew install petere/postgresql/postgresql@9.6`

results in
```
brew install petere/postgresql/postgresql@9.6
==> Installing postgresql@9.6 from petere/postgresql
==> Downloading https://ftp.postgresql.org/pub/source/v9.6.19/postgresql-9.6.19.tar.bz2
Already downloaded: /Users/fuh000c/Library/Caches/Homebrew/downloads/2836759a8927c699f1ac1f8edb5dd16ef1afd7987d448558bc0c7b0cc13eb215--postgresql-9.6.19.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/postgresql@9.6/9.6.19 --enable-dtrace --enable-nls --with-bonjour --with-gssapi --with-ldap --with-libxml --with-libxslt --with-o
Last 15 lines from /Users/fuh000c/Library/Logs/Homebrew/postgresql@9.6/01.configure:
checking for strtoll... yes
checking for strtoull... yes
checking whether strtoll is declared... yes
checking whether strtoull is declared... yes
checking for rl_completion_append_character... yes
checking for rl_completion_matches... yes
checking for rl_filename_completion_function... yes
checking for rl_reset_screen_size... yes
checking for append_history... yes
checking for history_truncate_file... yes
checking test program... ok
checking whether snprintf supports argument control... yes
checking whether long int is 64 bits... no
checking whether long long int is 64 bits... no
configure: error: Cannot find a working 64-bit integer type.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/petere/homebrew-postgresql/issues
```

I had successfully installed v12, then realized I needed to use v9.6 so installed it alongside v12 successfully (I'm using the pg_ctlcluster tools) 
But then realized the tooling (ie: psql) produced slightly different sql and messed up my Rails structure.sql/migrations.
So I `brew uninstalled` v12 and reinstalled v9.6 (thinking that might re-install the 9.6 psql binary) and am now stuck with the error above.

**Comment by frankhuster** [comment]
Here's a gist of the same error with `-verbose` output:
https://gist.github.com/frankhuster/eca5776a1ebbeef1586bd9dc13f05856

**Comment by frankhuster** [comment]
Followup
```
brew install postgresql@9.6
```
worked.
(note the missing `petere/postgresql`)

**Comment by AdeshAtole** [comment]
*If anyone is facing this for postgresql@9.3*
`brew edit postgresql@9.3`

find `args` inside `install`, andd add following option
`CFLAGS=-Wno-error=implicit-function-declaration`

And then try installing again

**Comment by hienpham-teamunify** [comment]
@AdeshAtole you saved my life, your solution also worked with postgresql@9.1
Thank you
