### ISSUE TITLE
Unable to install postgres@9.3 on MacOS Catalina (10.15.7) or MacOS Big Sur (11.1)

### ISSUE THREAD

**Issue by adamawolf** [petere/homebrew-postgresql#58]
Hello, I've got a database created by postgreSQL 9.3 that has been orphaned. In order to upgrade it I apparently need to re-install 9.3. I found your formulae from [this blog post](https://blog.andrewray.me/upgrading-from-postgres-9-3-on-osx/) and attempted to follow the steps.

```
brew tap petere/postgresql
brew install postgresql-9.3
```

Unfortunately, the install fails with:

```
Last 15 lines from /Users/adamawolf/Library/Logs/Homebrew/postgresql@9.3/01.configure:
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for strerror_r... yes
checking for getpwuid_r... yes
checking for gethostbyname_r... no
checking whether getpwuid_r takes a fifth argument... yes
checking whether strerror_r returns int... yes
checking for ldap_bind in -lldap... yes
checking for ldap_simple_bind in -lldap_r... yes
checking test program... ok
checking whether printf supports argument control... yes
checking whether long int is 64 bits... no
checking whether long long int is 64 bits... no
configure: error: Cannot find a working 64-bit integer type.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/petere/homebrew-postgresql/issues
```

From my research this seemed to be about a `gcc` issue in Big Sur. I tried this same process on a Catalina Mac, but it had the same results.

Entire `/Users/adamawolf/Library/Logs/Homebrew/postgresql@9.3/01.configure` is attached.

[01.configure.txt](https://github.com/petere/homebrew-postgresql/files/5839233/01.configure.txt)

**Comment by adamawolf** [comment]
Operating under the assumption that changes to apples `gcc` were the cause (inappropriately inserting `-Werror` as default) I was able to find a workaround.

1. Download an older command tools from https://developer.apple.com/download/more (I chose Command Line Tools for Xcode 11.5). Install.
2. Run `brew install postgresql-9.3`. The first time I tried this I hit a new error: `configure: error: header file <perl.h> is required for Perl`. To work around this new error:
3. `brew edit petere/postgresql/postgresql@9.3`, replace `--with-perl` with `--without-perl`. Save.
4. Run `brew install petere/postgresql/postgresql@9.3`.

It worked. I now have 9.3 installed on the Catalina machine and should be able to migrate my data.

**Comment by ajen010** [comment]
I tried to install postgresql@9.3 as well. I installed Command Line Tools for 11.5, brew edited postgresql@9.3 and replaced --with-perl with --without-perl and run brew install postgresql@9.3. It errored out again at configure: error: Cannot find a working 64-bit integer type.

**Comment by petere** [comment]
I think PostgreSQL major versions 9.4 and older are now dead on newer macOS because of this. Fixes for this exist in newer major versions and could be backpatched in theory, but these older versions are no longer maintained upstream.

**Comment by simonmichael** [comment]
For others in this situation, I found a good solution was to run postgres in ubuntu instead, via Canonical's multipass.
